"""Add leave management system

Revision ID: 0f79cd0e8a48
Revises: a51f4f488e9e
Create Date: 2026-04-25 08:47:13.959247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f79cd0e8a48'
down_revision = 'a51f4f488e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'personal', 'maternity', 'paternity', name='leave_type_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_requested', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='leave_status_enum'), nullable=False),
    sa.Column('applied_date', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['emp.eno'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['emp.eno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp'))
        batch_op.create_unique_constraint('unique_payroll', ['emp', 'month', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payroll', type_='unique')
        batch_op.create_index(batch_op.f('emp'), ['emp', 'month', 'year'], unique=True)

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    op.drop_table('leave')
    # ### end Alembic commands ###
