"""Attendance

Revision ID: 385b3257928f
Revises: e1a2b3c4d5f6
Create Date: 2026-03-21 09:34:02.696904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385b3257928f'
down_revision = 'e1a2b3c4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('att',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['emp.eno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    op.drop_table('att')
    # ### end Alembic commands ###
