"""Message for Flask Demo1

Revision ID: 60864291168e
Revises: 66bb0ebd547e
Create Date: 2026-03-14 08:39:53.982194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60864291168e'
down_revision = '66bb0ebd547e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dept', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dept', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
