"""Message for Flask Demo

Revision ID: 66bb0ebd547e
Revises: 
Create Date: 2026-03-13 08:55:45.050931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bb0ebd547e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dname', sa.String(length=20), nullable=False),
    sa.Column('loc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dept')
    # ### end Alembic commands ###
