"""User

Revision ID: 72abcfe066d8
Revises: 3d9c4571852a
Create Date: 2026-03-18 08:46:47.324736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72abcfe066d8'
down_revision = '3d9c4571852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
