"""Add half-day leave support

Revision ID: 7ceb2cf2a93f
Revises: 0f79cd0e8a48
Create Date: 2026-04-25 08:53:00.675665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ceb2cf2a93f'
down_revision = '0f79cd0e8a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_half_day', sa.Boolean(), nullable=True))
        batch_op.alter_column('days_requested',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp'))
        batch_op.create_unique_constraint('unique_payroll', ['emp', 'month', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payroll', type_='unique')
        batch_op.create_index(batch_op.f('emp'), ['emp', 'month', 'year'], unique=True)

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('days_requested',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('is_half_day')

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    # ### end Alembic commands ###
