"""Payroll1

Revision ID: a350eadf72ab
Revises: 445133e96a4a
Create Date: 2026-03-26 09:17:36.620766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a350eadf72ab'
down_revision = '445133e96a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('unique_payroll'))
        batch_op.drop_constraint(batch_op.f('payroll_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'emp', ['emp'], ['eno'])
        batch_op.drop_column('emp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payroll_ibfk_1'), 'emp', ['emp_id'], ['eno'])
        batch_op.create_index(batch_op.f('unique_payroll'), ['emp_id', 'month', 'year'], unique=True)
        batch_op.drop_column('emp')

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    # ### end Alembic commands ###
