"""Add announcements and comments

Revision ID: a51f4f488e9e
Revises: da225fe1f44c
Create Date: 2026-04-23 08:43:50.034689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a51f4f488e9e'
down_revision = 'da225fe1f44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['emp.eno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['emp.eno'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['announcement_comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp'))
        batch_op.create_unique_constraint('unique_payroll', ['emp', 'month', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payroll', type_='unique')
        batch_op.create_index(batch_op.f('emp'), ['emp', 'month', 'year'], unique=True)

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    op.drop_table('announcement_comment')
    op.drop_table('announcement')
    # ### end Alembic commands ###
