"""Message for Flask Employee

Revision ID: add540be8afe
Revises: d56b250ed444
Create Date: 2026-03-16 08:53:02.535521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add540be8afe'
down_revision = 'd56b250ed444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emp',
    sa.Column('eno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ename', sa.String(length=20), nullable=False),
    sa.Column('sal', sa.Float(), nullable=True),
    sa.Column('deptid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deptid'], ['dept.id'], ),
    sa.PrimaryKeyConstraint('eno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp')
    # ### end Alembic commands ###
