"""Payroll

Revision ID: afd51e8e0ffa
Revises: 385b3257928f
Create Date: 2026-03-26 08:56:47.605985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afd51e8e0ffa'
down_revision = '385b3257928f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    # ### end Alembic commands ###
