"""Image upload

Revision ID: c583168c6475
Revises: 72abcfe066d8
Create Date: 2026-03-19 09:23:44.077304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c583168c6475'
down_revision = '72abcfe066d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
