"""Message for Flask Date changes

Revision ID: d56b250ed444
Revises: 60864291168e
Create Date: 2026-03-14 09:02:14.550850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd56b250ed444'
down_revision = '60864291168e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dept', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dept', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
