"""PayrollNew

Revision ID: ff48899d76ae
Revises: afd51e8e0ffa
Create Date: 2026-03-26 09:07:12.037340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff48899d76ae'
down_revision = 'afd51e8e0ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['emp.eno'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id', 'month', 'year', name='unique_payroll')
    )
    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emp_id'))

    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emp_id'), ['emp_id', 'month', 'year'], unique=True)

    op.drop_table('payroll')
    # ### end Alembic commands ###
